# Generated by Django 4.2.7 on 2025-06-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_app', '0002_alter_ftpuser_ftp_directory_sharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpuser',
            name='ftp_directory',
            field=models.CharField(max_length=255),
        ),
    ]
